### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by jaasaria** [HeroSony/AuthRolePermission#1]
hi, im new in laravel and wanted to try your project. Can you please give me instruction how to install and setup database for testing? thanks in advance

**Comment by HeroSony** [comment]
-	Clone or Download project
-	Change .env.example to .env ( config DB username and password)
-	Open command prompt from local project and run `composer install` if you get `Fatal error: Call to undefined method Illuminate\Foundation\Application::bindShared()`, try to find EntrustServiceProvider.php and modify `bindShared` to `singleton`
-	Run `php artisan key:generate` for generate a new key

**Comment by jaasaria** [comment]
thanks dude:)
